#!/bin/bash
set -eo pipefail

SCRIPT=$(dirname $0)

TYPE=$(cat $SCRIPT/type.mem)

if [[ $TYPE != "pod" ]]; then
  echo "The last k8 get call must target pods"
  exit 1
fi

NAMESPACE=$(cat $SCRIPT/namespace.mem)
INDEX=$1
INDEX=$((INDEX+1))

ID=$(cat $SCRIPT/output.mem | sed -n "$INDEX"p | awk '{print $1}')

echo kubectl exec -it $ID -n $NAMESPACE ${@:2}
kubectl exec -it $ID -n $NAMESPACE ${@:2}
