#!/bin/bash
set -eo pipefail

SCRIPT=$(dirname $0)

TYPE=$(cat $SCRIPT/type.mem)

if [[ $TYPE != "pod" ]]; then
  echo "The last k8 get call must target pods"
  exit 1
fi

NAMESPACE=$(cat $SCRIPT/namespace.mem)
INDEX=$1
INDEX=$((INDEX+1))

ID=$(cat $SCRIPT/output.mem | sed -n "$INDEX"p | awk '{print $1}')

NODE_NAME=$(kubectl get $TYPE $ID -n $NAMESPACE -o=jsonpath='{.spec.nodeName}')
PROVIDER_ID=$(kubectl get node $NODE_NAME -o=jsonpath='{.spec.providerID}' | grep -o i-.*)
REGION=$(kubectl get node $NODE_NAME -ojson | jq -r '.metadata.labels["topology.kubernetes.io/region"]')
export AWS_REGION=$REGION
aws ssm start-session --target $PROVIDER_ID --document-name SSM-ec2-user